version: '3.8'

services:
  lagradar:
    build: .
    container_name: kafka-lag-radar
    ports:
      - "9090:9090"
    environment:
      - BROKERS=kafka1:9092,kafka2:9092,kafka3:9092
      - SCRAPE_INTERVAL=30
    command: ["-brokers", "${BROKERS}", "-interval", "${SCRAPE_INTERVAL:-30}"]
    networks:
      - monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./kafka_lag_alerts.yml:/etc/prometheus/kafka_lag_alerts.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge
volumes:
  prometheus_data: