global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'lagradar'
    static_configs:
      - targets: ['lagradar:8080']
    metrics_path: /metrics
    scrape_interval: 30s