apiVersion: v1
kind: ServiceAccount
metadata:
  name: lagradar
  namespace: monitoring
  labels:
    app: lagradar

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lagradar
  labels:
    app: lagradar
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lagradar
  labels:
    app: lagradar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lagradar
subjects:
  - kind: ServiceAccount
    name: lagradar
    namespace: monitoring