apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lagradar
  namespace: monitoring
  labels:
    app: lagradar
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: lagradar
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node