# LagRadar Configuration for Local K8s Testing

collector:
  window:
    size: 20
    min_size: 5
  check_interval: "30s"
  max_concurrency: 10
  thresholds:
    stalled_consumption_rate: 0.1
    rapid_lag_increase_rate: 100.0
    lag_trend_threshold: 0.1
    inactivity_timeout: "5m"

clusters:
  - name: "local-kafka"
    enabled: true
    brokers:
      - 192.168.49.2:30092

http:
  address: :8080
  metrics_path: /metrics

server:
  api:
    enabled: true
    address: "0.0.0.0:8080"
    read_timeout: "30s"
    write_timeout: "30s"