# LagRadar Configuration

kafka:
  brokers:
    - kafka-1:29092
    - kafka-2:29093
    - kafka-3:29094

collector:
  window:
    size: 20
    min_size: 5
  check_interval: "30s"
  max_concurrency: 10
  thresholds:
    stalled_consumption_rate: 0.1
    rapid_lag_increase_rate: 100.0
    lag_trend_threshold: 0.1
    inactivity_timeout: "5m"

http:
  address: :8080
  metrics_path: /metrics

server:
  api:
    enabled: true
    address: "0.0.0.0:8080"
    read_timeout: "30s"
    write_timeout: "30s"

rca:
  enabled: true
  redis_addr: "redis:6379" 
  redis_password: ""
  redis_db: 0
  stream_key: "lagradar:rca:events"
  max_retries: 3
  retry_interval: "1s"
  de_dupe_window: "5m"