name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-test-lint:
    name: "Verify (Go ${{ matrix.go }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.22', '1.21' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Cache Go build cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-${{ matrix.go }}-
            ${{ runner.os }}-go-build-
      - name: Install dependencies
        run: make deps
      - name: Verify (fmt, lint, tests)
        run: make verify
      - name: Upload coverage
        if: matrix.go == '1.22' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: coverage.txt
          path: coverage.txt
      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...

